### ISSUE TITLE
Support querying related records

### ISSUE THREAD

**Issue by andersme** [davetimmins/Anywhere.ArcGIS#22]
In the ArcGIS REST API, there is an ability to query records related to a particular objects. This appears to be the one thing I'm missing in this library.

https://developers.arcgis.com/rest/services-reference/query-related-records-feature-service-.htm

**Comment by davetimmins** [comment]
Yea I tend to only add things as I need them and haven't needed this previously. Happy to take a PR for this though if you're keen.
