### ISSUE TITLE
Invalid/Wrong Search Parameter used for Custom Geocode -findAddressCanidates query

### ISSUE THREAD

**Issue by keithdougherty** [davetimmins/Anywhere.ArcGIS#23]
https://github.com/davetimmins/Anywhere.ArcGIS/blob/987b2dcf00e951c8b500cdd1b865f9f68b7eb454/src/Anywhere.ArcGIS/Operation/CustomGeocode.cs#L25

Every Ersi Geocoder service I ran "findAddressCanidates" query against is expecting a "SingleLine" parameter, the "Text" parameter returns no results when searching for a known address or parcel number, where as the "SingleLine" returns the expected results. 

Even the ESRI world geocode service expecting this parameter for this query
URL: "http://geocode.arcgis.com/arcgis"
EndPoint: "/World/GeocodeServer"

**Comment by davetimmins** [comment]
I must've added that as the `suggest` operation returns the result as text (and magic key), pretty easy fix though. Cheers.

**Comment by davetimmins** [comment]
If you use the myget feed you can test the fix out. If it's OK I'll publish a new version to NuGet.

`Install-Package Anywhere.ArcGIS -Version 1.5.0-dev50 -Source https://www.myget.org/F/0b0e5c5f92fe4ccbba32eec8c0bb4c22/api/v3/index.json`

**Comment by keithdougherty** [comment]
Looks good to me, thanks
