### ISSUE TITLE
findAddressCanidates - incorrect shape expected in response - only handles Points

### ISSUE THREAD

**Issue by keithdougherty** [davetimmins/Anywhere.ArcGIS#24]
https://github.com/davetimmins/Anywhere.ArcGIS/blob/987b2dcf00e951c8b500cdd1b865f9f68b7eb454/src/Anywhere.ArcGIS/Operation/CustomGeocode.cs#L71

This query can return any shape, but it is currently coded to only handle deserializing a Point, this causes any result that is any other shape, such as a polygon for Parcels, to not get deserialized.

**Comment by davetimmins** [comment]
Do you have a sample request that returns something other than a point? All the samples in the online documentation just show location as a point.

**Comment by keithdougherty** [comment]
Sure, some of our clients host their own geocoder service which basically searches through their own self hosted GIS Databases and services.  Allowing them to create through own parcels or spatial collections in varies different shapes.  for an example the below query returns a parcel with a shape of a polygon:

https://energovgis-dev.tylerhost.net/arcgis/rest/services/SLO/Crisco/GeocodeServer/findAddressCandidates?Address=&City=&Region=&Country=&ZIP=&SingleLine=052-201-003&category=&outFields=&maxLocations=&outSR=&searchExtent=&location=&distance=&magicKey=&f=html

While it may not be the best approach, below is the code I used as a work around for the time being

    public class GeoCodeInput

    {
        public string EndPoint { get; set; }

        public string Text { get; set; }

        public int OutputSpatialReferenceWkId { get; set; } = 0;
    }

    [DataContract]
    public class CustomGeocodeInput : SingleInputCustomGeocode
    {
        public CustomGeocodeInput(ArcGISServerEndpoint serverEndpoint) : base(serverEndpoint)
        {

        }

        [DataMember(Name = "singleLine")]
        public string SingleLine { get; set; }
    }

    [DataContract]
    public class CustomGeocodeResponse : PortalResponse
    {
        [DataMember(Name = "spatialReference")]
        public SpatialReference SpatialReference { get; set; }

        [DataMember(Name = "candidates")]
        public CustomCanidate[] Candidates { get; set; }

    }

    [DataContract]
    public class CustomCanidate
    {
        [DataMember(Name = "address")]
        public string Address { get; set; }

        [DataMember(Name = "location")]
        public object Location { get; set; }

        [DataMember(Name = "score")]
        public double Score { get; set; }

        [DataMember(Name = "attributes")]
        public Dictionary<string, object> Attributes { get; set; }

        public IGeometry geometry = null;
    }

        public async Task<CustomCanidate> GeoCode(GeoCodeInput geoCodeInput)
        {

            CustomCanidate canidate = null;

            EnsureInitialized();

            CustomGeocodeInput customGeocode = new CustomGeocodeInput(new ArcGISServerEndpoint(_restUrl + geoCodeInput.EndPoint))
            {
                SingleLine = geoCodeInput.Text,
                OutputSpatialReference = new SpatialReference { Wkid = geoCodeInput.OutputSpatialReferenceWkId },
                OutFields = new List<string> { "*" }
            };

            CustomGeocodeResponse result = await _portal.Geocode(customGeocode);

            if (result.Candidates != null && result.Candidates.Count() > 0)
            {
                canidate = result.Candidates.FirstOrDefault();

                if (canidate.Location != null)
                {
                    //Geometry is a polyline
                    Point point = JsonConvert.DeserializeObject<Point>(canidate.Location.ToString());
                    if (point != null && (point.X != 0 || point.Y != 0))
                        canidate.geometry = point;

                    //Geometry is a polygon
                    Polygon polygon = JsonConvert.DeserializeObject<Polygon>(canidate.Location.ToString());
                    if (polygon != null && polygon.Rings != null)
                        canidate.geometry = polygon;

                    //Geometry is a polyline
                    Polyline polyline = JsonConvert.DeserializeObject<Polyline>(canidate.Location.ToString());
                    if (polyline != null && polyline.Paths != null)
                        canidate.geometry = polyline;

                    //Geometry is a MultiPoint
                    MultiPoint multiPoint = JsonConvert.DeserializeObject<MultiPoint>(canidate.Location.ToString());
                    if (multiPoint != null && multiPoint.Points != null)
                        canidate.geometry = multiPoint;
                }
            }

            return canidate;
        }

**Comment by davetimmins** [comment]
There's a `CustomGeocode` operation in the myget package that allows you to specify the geometry response type as a constraint

**Comment by davetimmins** [comment]
e.g. https://github.com/davetimmins/Anywhere.ArcGIS/blob/5ed2d97a3b753085464628d40c7433ea92ccc708/tests/Anywhere.ArcGIS.Test.Integration/GeocodeTests.cs#L89
