### ISSUE TITLE
No method exposed to use CustomGeocode - findAddressCanidates query

### ISSUE THREAD

**Issue by keithdougherty** [davetimmins/Anywhere.ArcGIS#25]
https://github.com/davetimmins/Anywhere.ArcGIS/blob/987b2dcf00e951c8b500cdd1b865f9f68b7eb454/src/Anywhere.ArcGIS/PortalGateway.cs#L332

There is a method to geocode, which is using the "find" query, however there is no method being exposed to handle the "findAddressCanidates" query, which uses the CustomGeocode class

**Comment by davetimmins** [comment]
Its the `SingleInputCustomGeocode` operation, you can add it to your own gateway if you need to call it.

**Comment by davetimmins** [comment]
The reason it isn't included is because I never got round to needing to use it. I only added the operation as I was using other related ones and it was similar

**Comment by keithdougherty** [comment]
Sure, it wasn't a big deal to implement using the Get in the PortalGatewayBase class from our own gateway class.  Just wanted to let you know that there wasn't a virtual method that accepts the SingleInputCustomGeocode operation in the PortalGateway class and only one for the SingleInputGeocode operation.  But like I said, not a big deal.

**Comment by davetimmins** [comment]
There's a `CustomGeocode` operation in the myget package
