### ISSUE TITLE
How I can get all features from a Query

### ISSUE THREAD

**Issue by mfandre** [davetimmins/Anywhere.ArcGIS#28]
The arcserver usually return maximum 1000 records. How can I do a query to get all the features?

**Comment by davetimmins** [comment]
That's a setting controlled by ArcGIS Server itself. If you don't want to change that setting then you can do the query in batches and set the offset (so long as the version of AGS supports it). There is a `BatchQuery` method you can call which wraps the multiple queries for you see https://github.com/davetimmins/Anywhere.ArcGIS/blob/1d012a394124888d44326155d1af0a5d8863cb67/src/Anywhere.ArcGIS/PortalGatewayBase.cs#L219

**Comment by mfandre** [comment]
@davetimmins can you give me an example how I can pass some pagination. Sorry it didnt clear for me.

Thsi do all job, or I need to do something else?

```
            var gateway = new PortalGateway(server); //"http://app.anp.gov.br/arcgis/"

            var query = new Query((service + "/MapServer/" + layer).AsEndpoint())
            {
                Where = "1=1"
            };
            query.ReturnGeometry = true;
            var result = await gateway.BatchQuery<Anywhere.ArcGIS.Common.Point>(query);
            var count = result.Features.Count();
```

**Comment by davetimmins** [comment]
Yea that will do it, also you don't need to set the where clause as it defaults to 1=1

**Comment by mfandre** [comment]
Another question, how I can convert the result to geojson string?
