### ISSUE TITLE
How convert to GeoJson

### ISSUE THREAD

**Issue by mfandre** [davetimmins/Anywhere.ArcGIS#29]
Guys how I can convert this result to GeoJson string?

```
  var gateway = new PortalGateway(server); //"http://app.anp.gov.br/arcgis/"

            var query = new Query((service + "/MapServer/" + layer).AsEndpoint())
            {
                Where = "1=1"
            };
            query.ReturnGeometry = true;
            var result = await gateway.BatchQuery<Anywhere.ArcGIS.Common.Point>(query);
            var count = result.Features.Count();

```

**Comment by davetimmins** [comment]
You can call ToFeatureCollection on the list of features to get them as GeoJSON

**Comment by mfandre** [comment]
Like this:
`
var featureCollectionGeoJson = FeatureCollectionExtensions.ToFeatureCollection<Anywhere.ArcGIS.Common.Point>(result.Features.ToList());
`

I need  to cast to tolist??? It could be a problem if my list was too big... What the possibility to change this method to Enumerable?

**Comment by davetimmins** [comment]
It is manipulating the objects anyway so I don't think it would make a difference. Feel free to benchmark it though and if it does I'd be happy to take a PR.

**Comment by davetimmins** [comment]
Also, as it is an extension method you could do `result.Features.ToList().ToFeatureCollection();`
