### ISSUE TITLE
Problems with BatchQuery

### ISSUE THREAD

**Issue by mgayheart1** [davetimmins/Anywhere.ArcGIS#31]
I found two issues when testing BatchQuery using Azure Functions 1.x against an AGOL Hosted Feature Service:
1. I get an error like this: 

> "message": "Exception while executing function: <function> -> Nullable object must have a value.",
"errorDetails": "Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: <function> ---> System.InvalidOperationException : Nullable object must have a value.\r\n   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)\r\n   at async Anywhere.ArcGIS.PortalGatewayBase.BatchQuery[T](Query queryOptions,CancellationToken ct)\r\n
..."

I was able to fix this by changing PortalGatewayBase line 242 from:
```C#
exceeded = result.ExceededTransferLimit.HasValue && innerResult.ExceededTransferLimit.Value;
```
to
```C#
exceeded = result.ExceededTransferLimit.HasValue && innerResult.ExceededTransferLimit.HasValue && innerResult.ExceededTransferLimit.Value;
```

2. I wasn't actually getting back all the results from the feature service. I was expecting 5000+ features, but I was only getting the results from the first query. I was able to fix this by changing PortalGatewayBase line 241 from:
```C#
result.Features.ToList().AddRange(innerResult.Features);
```
to
```C#
result.Features = result.Features.Concat<Feature<T>>(innerResult.Features);
```

I didn't have time to test against various types of AGS services so it is possible that these changes were unique to my setup, but wanted to send them along just in case.

Thanks for sharing this great repo!

**Comment by davetimmins** [comment]
Yea those changes seem to work, I've pushed them  to the dev branch so the myget package (1.6.1-dev59) has them if you wanted to test it out.
