### ISSUE TITLE
Enhancement: Add drawingInfo to `ServiceLayerDescriptionResponse`

### ISSUE THREAD

**Issue by beginor** [davetimmins/Anywhere.ArcGIS#38]
Thanks for the great work, but I found `drawingInfo` is missing from type `ServiceLayerDescriptionResponse`， would you add it?

My test code is:

```c#
var gateway = new ArcGISOnlineGateway(
    "https://sampleserver6.arcgisonline.com/arcgis"
);
var response = await gateway.DescribeLayer(endpoint);
var endpoint = new ArcGISServerEndpoint(
    "Military/MapServer/3"
);
```

and the service with json response is: https://sampleserver6.arcgisonline.com/arcgis/rest/services/Military/MapServer/3?f=pjson

**Comment by davetimmins** [comment]
Hi, I decided to leave drawing info out as there are lots of different combinations that are valid depending on the type of symbology used when the service is published. If you are just using it for a known service then your best solution is probably to extend the existing code to cater for that particular data. An example of the concept of adding your own operations is in the test project https://github.com/davetimmins/Anywhere.ArcGIS/blob/7bece4a0e627b2d768e6f4435764991299067bec/tests/Anywhere.ArcGIS.Test.Integration/ArcGISGatewayTests.cs#L17

**Comment by beginor** [comment]
OK, I will close this issue, thanks for your response.
