### ISSUE TITLE
MinimumScale/MaximumScale on ServiceLayerDescriptionResponse should be double

### ISSUE THREAD

**Issue by mgayheart1** [davetimmins/Anywhere.ArcGIS#46]
I published a hosted feature layer from Pro to AGOL using AGOL defined scales for when the layer will draw. The resulting layer has a Min. Scale property of 577790.554289. When I try to batch query the layer, I get an error:
System.Private.CoreLib: Exception while executing function: XXXX. Newtonsoft.Json: Input string '577790.554289' is not a valid integer. Path 'minScale', line 1, position 1442.

Searching the code for MinimumScale, there are 3 places in the code. Two of them are defined as double? and one is defined as int (ServiceLayerDescriptionResponse class). Seems like MinimumScale and MaximumScale on this class should be changed to double?.

**Comment by mgayheart1** [comment]
I am looking into this.

**Comment by davetimmins** [comment]
released in v1.9.1 thanks
