### ISSUE TITLE
FeatureServers with domain information cause JSON parsing error

### ISSUE THREAD

**Issue by spaddlewit** [davetimmins/Anywhere.ArcGIS#52]
[DataMember(Name = "domain")]
        public string Domain { get; set; }

Domain is a JSON object, not a string, so when queries are performed on feature servers with domain information, it causes a JSON parsing error.

Perhaps just remove the Domain property?

**Comment by davetimmins** [comment]
Do you have a URL I can look at that returns domains?

**Comment by spaddlewit** [comment]
No, but I can provide some samples:

    {
      "name": "PencilType",
      "type": "esriFieldTypeString",
      "alias": "Pencil Type",
      "sqlType": "sqlTypeOther",
      "length": 50,
      "domain": {
        "type": "codedValue",
        "name": "KindTypes",
        "codedValues": [
          {
            "name": "GoneHome",
            "code": "GH"
          },
          {
            "name": "ManyCatches",
            "code": "MC"
          }
        ]
      }
    },
    {
      "name": "RangeType",
      "type": "esriFieldTypeString",
      "alias": "Range Type",
      "sqlType": "sqlTypeOther",
      "length": 255,
      "domain": {
        "type": "codedValue",
        "name": "RangeTypes",
        "codedValues": [
          {
            "name": "CRP",
            "code": "CRP"
          },
          {
            "name": "Gone Saw Mix",
            "code": "Gone Saw Mix"
          },
          {
            "name": "Mind Green",
            "code": "Mind Green"
          },
          {
            "name": "Mommy Means",
            "code": "Mommy Means"
          },
          {
            "name": "Sign",
            "code": "Sign"
          },
          {
            "name": "Sand Gypsum",
            "code": "Sand Gypsum"
          },
          {
            "name": "Sand Gone Done What",
            "code": "Sand Gone Done What"
          },
          {
            "name": "Tiny Gunk",
            "code": "Tiny Gunk"
          },
          {
            "name": "Not Defined",
            "code": "Not Defined"
          }
        ]
      },
      "defaultValue": null
    },

**Comment by davetimmins** [comment]
You can test a fix using the myget feed https://www.myget.org/feed/0b0e5c5f92fe4ccbba32eec8c0bb4c22/package/nuget/Anywhere.ArcGIS/1.9.1-dev106

**Comment by spaddlewit** [comment]
How do I hook up MyGet as NuGet package source?

**Comment by davetimmins** [comment]
published in v1.10.0
