### ISSUE TITLE
PointsCollection.Points returns wrong points on geometries with Z values

### ISSUE THREAD

**Issue by gunmiosb** [davetimmins/Anywhere.ArcGIS#63]
The method:
 `public List<Point> Points
        {
            get
            {
                return this.Select(point => point != null ? new Point { X = point.First(), Y = point.Last() } : null)
                    .Where(p => p != null)
                    .ToList();
            }
        }`

in IGeometry returns points with coordinates {X=x,Y=z} for requests with Z values.

**Comment by davetimmins** [comment]
Thanks, you can use this fix in the myget feed until I update NuGet https://www.myget.org/feed/0b0e5c5f92fe4ccbba32eec8c0bb4c22/package/nuget/Anywhere.ArcGIS
