### ISSUE TITLE
Can create get urls that are to long to esri server

### ISSUE THREAD

**Issue by doublej42** [davetimmins/Anywhere.ArcGIS#67]
You have a default MaximumGetRequestLength that switches to POST. 

https://github.com/davetimmins/Anywhere.ArcGIS/blob/c95c7630815a2ad524c0114c8a346a19c7dc95e8/src/Anywhere.ArcGIS/PortalGatewayBase.cs#L112

It checked this length then it adds the token and a few other things.

https://github.com/davetimmins/Anywhere.ArcGIS/blob/c95c7630815a2ad524c0114c8a346a19c7dc95e8/src/Anywhere.ArcGIS/PortalGatewayBase.cs#L695

My token was 193 letters.

With the &f=json&token= this came to 207 extra letters.

It would be good to check the url after this is added or just reduce the max default max to 1800 or something reasonable (I have no idea the range of token lengths).

Workaround:
```csharp
var secureGateway = await PortalGateway.Create("https://geoportal.example.com/server/", "username","password1");
secureGateway.MaximumGetRequestLength = 1000;
```

**Comment by davetimmins** [comment]
Good catch, I've moved the check to after the token generation. It'll be in the next release, or its in the myget feed now.
