### ISSUE TITLE
Timeinterval is not necessarily an integer value

### ISSUE THREAD

**Issue by bveldkamp** [davetimmins/Anywhere.ArcGIS#74]
I have a service that is time enabled, and has an interval of roughly 12 days. It returns this:

```
"timeInfo": {
	"timeExtent": [
		1546300800000,
		253402214400000
	],
	"timeReference": null,
	"timeRelation": "esriTimeRelationOverlaps",
	"defaultTimeInterval": 0.39425893413496776,
	"defaultTimeIntervalUnits": "esriTimeUnitsMonths",
	"defaultTimeWindow": 0,
	"defaultTimeWindowUnits": "esriTimeUnitsMonths",
	"hasLiveData": false
},
```

On which DescribeServices() throws an error: _One or more errors occurred. (Input string '0.39425893413496776' is not a valid integer. Path 'timeInfo.defaultTimeInterval', line 1, position 3188_

**Comment by davetimmins** [comment]
Changed that to a double in release 2.0.1
