### ISSUE TITLE
HTTP Referrer Header

### ISSUE THREAD

**Issue by gcapnias** [davetimmins/Anywhere.ArcGIS#76]
Hi,

Just a question - how is it possible to add HTTP Referrer Header in order to access an ArcGIS MapServer service?

I cannot locate something like, in the examples...

Thanks,
George J.

**Comment by davetimmins** [comment]
You can pass in your own httpClientFunc when creating a gateway, this can be setup however you like. Basically it will be your own version of this function https://github.com/davetimmins/Anywhere.ArcGIS/blob/a64cfe8a9758ac2600261b48f3349c5feea92758/src/Anywhere.ArcGIS/HttpClientFactory.cs#L20
