### ISSUE TITLE
Overridable properties for ArcGISServerEndpoint

### ISSUE THREAD

**Issue by npalla-tyler** [davetimmins/Anywhere.ArcGIS#78]
We ran into an issue if MapServer and GeoCode server URLs are on 2 different physical servers. In the current implementation, base the path of the Map-Server URL (RootUrl) and the relative path of GeoCode Server URL's are combined to get the final URL to get GeoCode. It would be great if we have the ability to override RelativeUrl property and BuildAbsoluteUrl method as virtual in ArcGISServerEndpoint. This will give us the flexibility to have an absolute URL for Geocode Server. Also, it would be great if you can update SingleInputCustomGeocode constructors to pass IEndPoint instead of ArcGISServerEndpoint. Also, it would be great if we can add another constructor to the same class to pass the endpoint as is to the base class instead of letting the base class create a new instance of ArcGISServerEndpoint. 

Thanks a lot for all your efforts.

**Comment by davetimmins** [comment]
If you have resources on separate servers (URLs) you can just use a different gateway instance.
